services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "3000:3000" # Map the container's port 3000 to the host's port 3000
    environment:
      NODE_ENV: production
      PORT: 3000
    volumes:
      - .:/app
      - /app/node_modules
